### ISSUE TITLE
EDU file format

### ISSUE THREAD

**Issue by rknaebel** [sougata-ub/edu-ap#1]
Hi Sougata,
I just wanted to try your tool but stumbled over the input format of the EDU file. The README refers to the edu segmenter, but your code assumes some binary pickled format instead. I wonder whether you have some pre-processing script that might be useful to convert the generated EDU segments to your expected format.
Best wishes
René

**Comment by sougata-ub** [comment]
Please try out this notebook: https://github.com/sougata-ub/edu-ap/blob/main/Formatting_PE_dataset_EDU_parse_Notebook.ipynb
